
- name: Installing Apache2
  hosts: nodo2
  become: true
  tasks:
  
  - name: Update package list
    apt: 
     update_cache: yes
    
  - name: Instaling packages
    apt:
     name: "{{ packages }}"
    vars:
     packages:
      - apache2
      - libapache2-mod-php7.0
      - php7.0-fpm
      - php7.0-pgsql
      - php-xml
      - php7.0-gd
      - php7.0-mbstring
      - postgresql-client
   
  - name: Disabling default page
    command: a2dissite 000-default.conf
  
  - name: Enabling php configuration
    command: a2enmod proxy_fcgi setenvif
    command: a2enconf php7.0-fpm

  - name: Setting up drupal.conf
    copy:
     src: utils/etc/apache2/drupal.conf
     dest: /etc/apache2/sites-available/drupal.conf

  - name: Enabling drupal configuration
    command: a2ensite drupal.conf

    notify:
      - restart apache2

  handlers:
    - name: restart apache2
      service: 
        name: apache2 
        state: restarted
